version: '3.8'

services:
  api:
    container_name: best-movie-of-all-time-api
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    user: root
    command: npm run start:prod
    ports:
      - 8080:8080
    networks:
      - overlay
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      - MONGO_URI=mongodb://mongo:27017/best-movie

  mongo:
    image: mongo:latest
    container_name: best-movie-mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - overlay
    volumes:
      - mongo_data:/data/db

volumes:
  shared_database:
  mongo_data:

networks:
  overlay:
    driver: bridge