version: '3.8'

services:
  api:
    container_name: best-movie-of-all-time-api
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    user: root
    command: npm run start:prod
    ports:
      - 8080:8080
    networks:
      - overlay
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist

  mongo:
    image: mongo:latest
    container_name: best-movie-mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - overlay
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: best-movie-redis
    restart: always
    networks:
      - overlay
    volumes:
      - redis_data:/data

volumes:
  shared_database:
  mongo_data:
  redis_data:
    driver: local

networks:
  overlay:
    driver: bridge
